language: php
php:
- '7.0'
- '7.1'
- '7.2'
before_script:
 - composer install
script:
 - phpunit
after_success:
  - wget https://raw.githubusercontent.com/snkrsnkampa/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success
after_failure:
  - wget https://raw.githubusercontent.com/snkrsnkampa/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure
